# Generated by Django 5.2.1 on 2025-05-26 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REMTySprotesta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.AlterModelOptions(
            name='registrocontraloria',
            options={'verbose_name': 'Registro de Contraloría', 'verbose_name_plural': 'Registros de Contraloría'},
        ),
        migrations.AlterField(
            model_name='registrocontraloria',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrocontraloria',
            name='estatus',
            field=models.CharField(default='BORRADOR', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrocontraloria',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='registrocontraloria',
            table='registros_contraloria',
        ),
        migrations.CreateModel(
            name='RegistroCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REMTySprotesta.categoria')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REMTySprotesta.registrocontraloria')),
            ],
            options={
                'verbose_name': 'Registro-Categoría',
                'verbose_name_plural': 'Registros-Categorías',
                'db_table': 'registro_categorias',
                'unique_together': {('registro', 'categoria')},
            },
        ),
    ]
